baseURL = 'https://yugu0202.net/'
publishDir = "public"
languageCode = 'ja_jp'
title = "yugu0202 Portfolio"
theme = 'PaperMod'
googleAnalytics = "G-P09KBMEXDV"
analytics.google.SiteVerificationTag = "G-P09KBMEXDV"

[params.profileMode]
enabled = true
title = "Hi,I'm yugu0202"
subtitle = ''
imageUrl = "https://github.com/yugu0202.png"

[params]
socialIcons = [
    { name = 'twitter', url = 'https://twitter.com/yugu0202' },
    { name = 'github', url = 'https://github.com/yugu0202' },
]

[menu]
main = [
    { identifier = "Home", name = "Home", url = "/", weight = 10 },
    { identifier = "Skills", name = "Skills", url = "/skills/", weight = 20 },
    { identifier = "Works", name = "Works", url = "/works/", weight = 30 }
]
